metric:
  statsD:
    addr: 127.0.0.1:8125
    prefix: stats
    flushInterval: 100ms
    flushBytes: 1440
    options:
      sampleRate: 1.0
  scope:
    prefix: blueprint
    tags:
      service: blueprint
  interval: 1s
tracing:
  serviceName: blueprint
graphql:
  introspection: true
  dataloader:
    wait: 250us
  playground:
    route: /client
    name: local
    endpoint: /query
  route: /query
postgres:
  dsn: postgres://blueprint:insecure@localhost:5567/blueprint?sslmode=disable
  maxOpenConns: 5
  maxIdleConns: 3
  connMaxLifetime: 15m
  logLevel: debug
grpc:
  services:
    ms:
      target: localhost:8081
      maxConn: 10
      initConn: 1
      maxLifeDuration: 5m
      idleTimeout: 1s
  keepalive:
    clientParameters:
      time: 5m
      timeout: 10s
      permitWithoutStream: false