version: '3.7'
services:
  postgres:
    ports:
      - "5567:5432"
    volumes:
      - ../.tmp/postgres:/var/lib/postgresql/data
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d